package HelmCharts;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleInterpreted2;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.language.LanguageRuntime;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import HelmCharts.K8sManifest.QueriesGenerated;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Arrays;

public class Generator extends TemplateModuleInterpreted2 {

  public Generator(LanguageRegistry languageRegistry, LanguageRuntime sourceLanguage, jetbrains.mps.smodel.Generator generator) {
    super(languageRegistry, sourceLanguage, generator);
  }

  @NotNull
  @Override
  public SModuleReference getModuleReference() {
    return PersistenceFacade.getInstance().createModuleReference("6fd179ba-8359-46dd-b04c-54c92c007151(HelmCharts)");
  }

  @Override
  protected void fillTemplateModels(TemplateModuleInterpreted2.TemplateModels models) {
    models.templates("r:11322ce3-ed24-4920-9464-5d672ed58a19", QueriesGenerated.class);
    models.templates("r:76f27afd-a8a5-4221-960b-e152decb6534", HelmCharts.Kustomize.QueriesGenerated.class);
  }


  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[2];
    rv[0] = MetaAdapterFactory.getLanguage(0xdd310849d074035L, 0x939dcb69bd123423L, "K8sManifests");
    rv[1] = MetaAdapterFactory.getLanguage(0xb18cfcd3e5b435dL, 0xa24a6a55dd41b84dL, "Kustomise");
    return Arrays.asList(rv);
  }

}
