package K8sManifests.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ServiceSpec_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.testproperty$pssI));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty testproperty$pssI = MetaAdapterFactory.getProperty(0xdd310849d074035L, 0x939dcb69bd123423L, 0xd4e0ced66e17a1aL, 0xd4e0ced66e17a1dL, "testproperty");
  }
}
