package K8sManifests.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import K8sManifests.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import java.nio.charset.Charset;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Specification:
        return new Specification_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.Specification$j4)) {
        String fname = getFileName_Specification(root);
        String ext = getFileExtension_Specification(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), Charset.forName(getEncoding_Specification()), root);
        continue;
      }
    }
  }
  private static String getFileName_Specification(SNode node) {
    return "test.yaml";
  }
  private static String getFileExtension_Specification(SNode node) {
    return null;
  }
  private static String getEncoding_Specification() {
    return "UTF-8";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Specification$j4 = MetaAdapterFactory.getConcept(0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de234337383L, "K8sManifests.structure.Specification");
  }
}
