package HelmCharts.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int HelmChart = 0;
  public static final int HelmChartInfo = 1;
  public static final int HelmChartTemplates = 2;
  public static final int HelmChartValues = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL);
    builder.put(0xd7637c9ab225df3L, HelmChart);
    builder.put(0xd7637c9ab225df4L, HelmChartInfo);
    builder.put(0xd7637c9ab225e00L, HelmChartTemplates);
    builder.put(0xd7637c9ab225e01L, HelmChartValues);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
