---
apiVersion: v2
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
...
---
apiVersion: v1
kind: Pod
metadata:
  name: myCustomPod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
...
---
apiVersion: v2
kind: Pod
metadata:
  name: myCustomPod2
  namespace: default2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
...
