---
apiVersion: v2
kind: Pod
metadata:
  name: name
  namespace: namesapce
spec:
  containers:
    name: containername1  name: containername2
    image: image1         image: image2
    ports:                ports: 

...
---
apiVersion: v1
kind: Pod
metadata:
  name: myCustomPod
  namespace: default
spec:
  containers:
    name: portname2
    image: sdadsadsa
    ports: 

...
---
apiVersion: v2
kind: Pod
metadata:
  name: myCustomPod2
  namespace: default2
spec:
  containers:
    name: portname4
    image: sdadsa
    ports: 

...
