package K8sManifests.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.MapConfigBase;
import jetbrains.mps.generator.runtime.TemplateMappingConfiguration;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.runtime.MetaObjectContainer;

@Generated
public class Mapping_File extends MapConfigBase implements TemplateMappingConfiguration {
  public Mapping_File(@NotNull TemplateModel model) {
    super(new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "5176375271270819327"), "File", model, false, new MO());
  }

  /*package*/ static final class MO implements MetaObjectContainer {



  }
}
