package K8sManifests.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.ApplySink;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.runtime.MetaObjectContainer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.SNodePointer;

@Generated
public class Template extends TemplateDeclarationBase {

  public Template() {
    super(new MO());
  }

  public SNodeReference getTemplateNode() {
    return template_p4e4wd_a0a3;
  }

  @Override
  public void apply(TemplateContext context, ApplySink sink) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    final SNode tnode1 = environment.createOutputNode(myConcepts[0]);
    {
      TemplateContext context1 = context.subContext();
      {
        final List<SNode> tlist2 = new ArrayList<SNode>();
        final Iterable<SNode> loopList2 = QueriesGenerated.sourceNodesQuery_2_0(new SourceSubstituteMacroNodesContext(context1, loopMacroRef_p4e4wd_b0a0a1a1a2a5));
        for (SNode itnode2 : loopList2) {
          if (itnode2 == null) {
            continue;
          }
          TemplateContext context2 = context1.subContext(itnode2);
          final SNode tnode3 = environment.createOutputNode(myConcepts[1]);
          {
            TemplateContext context3 = context2.subContext();
            {
              final SNode tnode4 = environment.createOutputNode(myConcepts[2]);
              SNodeAccessUtil.setPropertyValue(tnode4, myProperties[0], QueriesGenerated.propertyMacro_GetValue_2_0(new PropertyMacroContext(context3, "default", propertyMacro_p4e4wd_c0a2a0a1a1a3a2a1a2a5)));
              SNodeAccessUtil.setPropertyValue(tnode4, myProperties[1], QueriesGenerated.propertyMacro_GetValue_2_1(new PropertyMacroContext(context3, "default", propertyMacro_p4e4wd_c0a2a1a1a1a3a2a1a2a5)));
              environment.aggregate(tnode3, myAggregationLinks[0], tnode4);
            }
          }
          tlist2.add(tnode3);
        }
        environment.aggregate(tnode1, myAggregationLinks[1], tlist2);
      }
      {
        final SNode tnode5 = environment.createOutputNode(myConcepts[3]);
        SNodeAccessUtil.setPropertyValue(tnode5, myProperties[2], QueriesGenerated.propertyMacro_GetValue_2_2(new PropertyMacroContext(context1, "default", propertyMacro_p4e4wd_c0a2a0a1a2a2a5)));
        SNodeAccessUtil.setPropertyValue(tnode5, myProperties[3], QueriesGenerated.propertyMacro_GetValue_2_3(new PropertyMacroContext(context1, "default", propertyMacro_p4e4wd_c0a2a1a1a2a2a5)));
        SNodeAccessUtil.setPropertyValue(tnode5, myProperties[4], QueriesGenerated.propertyMacro_GetValue_2_4(new PropertyMacroContext(context1, null, propertyMacro_p4e4wd_c0a2a2a1a2a2a5)));
        SNodeAccessUtil.setPropertyValue(tnode5, myProperties[5], QueriesGenerated.propertyMacro_GetValue_2_5(new PropertyMacroContext(context1, "default", propertyMacro_p4e4wd_c0a2a3a1a2a2a5)));
        environment.aggregate(tnode1, myAggregationLinks[2], tnode5);
      }
    }
    sink.add(null, TemplateUtil.singletonList(tnode1));
  }

  /*package*/ static final class MO implements MetaObjectContainer {
    @Override
    public SConcept[] concepts() {
      SConcept[] rv = new SConcept[4];
      rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, "HelmCharts"), 0xd7637c9ab225df3L, "HelmChart");
      rv[1] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, "HelmCharts"), 0xd7637c9ab225e00L, "HelmChartTemplate");
      rv[2] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, "HelmCharts"), 0xcbfdf38c8397c08L, "TemplateMetadata");
      rv[3] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, "HelmCharts"), 0xd7637c9ab225df4L, "HelmChartInfo");
      return rv;
    }

    @Override
    public SProperty[] properties() {
      SProperty[] rv = new SProperty[6];
      rv[0] = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xcbfdf38c8397c08L, 0xcbfdf38c8397c09L, "name");
      rv[1] = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xcbfdf38c8397c08L, 0xcbfdf38c8397c0bL, "namespace");
      rv[2] = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225df4L, 0xd7637c9ab22644bL, "name");
      rv[3] = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225df4L, 0xd7637c9ab22644eL, "version");
      rv[4] = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225df4L, 0xd7637c9ab226449L, "apiVersion");
      rv[5] = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225df4L, 0xd7637c9ab226452L, "kubeVersion");
      return rv;
    }


    @Override
    public SContainmentLink[] aggregations() {
      SContainmentLink[] rv = new SContainmentLink[3];
      rv[0] = MetaAdapterFactory.getContainmentLink(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225e00L, 0xcbfdf38c8397c0eL, "templateMetadata");
      rv[1] = MetaAdapterFactory.getContainmentLink(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225df3L, 0xd7637c9ab225dfcL, "helmChartTemplates");
      rv[2] = MetaAdapterFactory.getContainmentLink(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225df3L, 0xd7637c9ab225df7L, "helmChartInfo");
      return rv;
    }
  }
  private static final SNodePointer template_p4e4wd_a0a3 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019746839");
  private static final SNodePointer loopMacroRef_p4e4wd_b0a0a1a1a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019762518");
  private static final SNodePointer propertyMacro_p4e4wd_c0a2a0a1a1a3a2a1a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019763036");
  private static final SNodePointer propertyMacro_p4e4wd_c0a2a1a1a1a3a2a1a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019770797");
  private static final SNodePointer propertyMacro_p4e4wd_c0a2a0a1a2a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019747199");
  private static final SNodePointer propertyMacro_p4e4wd_c0a2a1a1a2a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019749983");
  private static final SNodePointer propertyMacro_p4e4wd_c0a2a2a1a2a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019756023");
  private static final SNodePointer propertyMacro_p4e4wd_c0a2a3a1a2a2a5 = new SNodePointer("r:6357e749-ef68-478f-98ea-f1b11fc9f288(K8sManifests.generator.templates@generator)", "1180114424019761272");
}
