package Kustomize.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Test_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("test: ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.test$fdAc));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty test$fdAc = MetaAdapterFactory.getProperty(0xf78af01f47cf499bL, 0xac7bdd5feb577906L, 0x31016338a4c74569L, 0x31016338a4c7456aL, "test");
  }
}
