package ManifestConverter.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptIManifest = createDescriptorForIManifest();
  /*package*/ final ConceptDescriptor myConceptManifestMetadata = createDescriptorForManifestMetadata();
  /*package*/ final ConceptDescriptor myConceptPod = createDescriptorForPod();
  /*package*/ final ConceptDescriptor myConceptPodSpec = createDescriptorForPodSpec();
  /*package*/ final ConceptDescriptor myConceptSpecification = createDescriptorForSpecification();
  /*package*/ final EnumerationDescriptor myEnumerationApiVersions = new EnumerationDescriptor_ApiVersions();
  /*package*/ final EnumerationDescriptor myEnumerationManifestKinds = new EnumerationDescriptor_ManifestKinds();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptIManifest, myConceptManifestMetadata, myConceptPod, myConceptPodSpec, myConceptSpecification);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.IManifest:
        return myConceptIManifest;
      case LanguageConceptSwitch.ManifestMetadata:
        return myConceptManifestMetadata;
      case LanguageConceptSwitch.Pod:
        return myConceptPod;
      case LanguageConceptSwitch.PodSpec:
        return myConceptPodSpec;
      case LanguageConceptSwitch.Specification:
        return myConceptSpecification;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationApiVersions, myEnumerationManifestKinds);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForIManifest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ManifestConverter", "IManifest", 0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de234364c8aL);
    b.interface_();
    b.origin("r:f90efb3c-595b-49f9-80ca-2be4c9074d04(ManifestConverter.structure)/5176375271270796426");
    b.version(2);
    b.property("apiVersion", 0x47d62de234364c8bL).type(MetaIdFactory.dataTypeId(0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de23435ebcdL)).origin("5176375271270796427").done();
    b.property("kind", 0x47d62de234364c8dL).type(MetaIdFactory.dataTypeId(0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de234335623L)).origin("5176375271270796429").done();
    b.aggregate("metadata", 0x47d62de234364c90L).target(0xdd310849d074035L, 0x939dcb69bd123423L, 0x59e2bd7dbb117259L).optional(true).ordered(true).multiple(false).origin("5176375271270796432").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForManifestMetadata() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ManifestConverter", "ManifestMetadata", 0xdd310849d074035L, 0x939dcb69bd123423L, 0x59e2bd7dbb117259L);
    b.class_(false, false, false);
    b.origin("r:f90efb3c-595b-49f9-80ca-2be4c9074d04(ManifestConverter.structure)/6476947561819239001");
    b.version(2);
    b.property("name", 0x59e2bd7dbb11725aL).type(PrimitiveTypeId.STRING).origin("6476947561819239002").done();
    b.property("namespace", 0x59e2bd7dbb135806L).type(PrimitiveTypeId.STRING).origin("6476947561819363334").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPod() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ManifestConverter", "Pod", 0xdd310849d074035L, 0x939dcb69bd123423L, 0x59e2bd7dbb117263L);
    b.class_(false, false, true);
    b.parent(0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de234364c8aL);
    b.origin("r:f90efb3c-595b-49f9-80ca-2be4c9074d04(ManifestConverter.structure)/6476947561819239011");
    b.version(2);
    b.aggregate("podSpec", 0x59e2bd7dbb117268L).target(0xdd310849d074035L, 0x939dcb69bd123423L, 0x59e2bd7dbb117258L).optional(true).ordered(true).multiple(false).origin("6476947561819239016").done();
    b.alias("Pod");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPodSpec() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ManifestConverter", "PodSpec", 0xdd310849d074035L, 0x939dcb69bd123423L, 0x59e2bd7dbb117258L);
    b.class_(false, false, false);
    b.origin("r:f90efb3c-595b-49f9-80ca-2be4c9074d04(ManifestConverter.structure)/6476947561819239000");
    b.version(2);
    b.property("containers", 0x59e2bd7dbb11725cL).type(PrimitiveTypeId.STRING).origin("6476947561819239004").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpecification() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ManifestConverter", "Specification", 0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de234337383L);
    b.class_(false, false, true);
    b.origin("r:f90efb3c-595b-49f9-80ca-2be4c9074d04(ManifestConverter.structure)/5176375271270609795");
    b.version(2);
    b.aggregate("manifests", 0x47d62de234337384L).target(0xdd310849d074035L, 0x939dcb69bd123423L, 0x47d62de234364c8aL).optional(true).ordered(true).multiple(true).origin("5176375271270609796").done();
    b.alias("Specification");
    return b.create();
  }
}
