package Kustomise.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Test_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("test:");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.test$D1nL));
  }

  private static final class PROPS {
    /*package*/ static final SProperty test$D1nL = MetaAdapterFactory.getProperty(0xb18cfcd3e5b435dL, 0xa24a6a55dd41b84dL, 0x74386e7f7909e0a1L, 0x74386e7f7909e0a2L, "test");
  }
}
