package HelmCharts.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class HelmChartTemplate_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("---");
    tgs.newLine();
    tgs.append("apiVersion: ");
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.apiVersion$RKxP).toString());
    tgs.newLine();
    tgs.append("kind: ");
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.kind$RPVc).toString());
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.templateMetadata$BXdE));
    tgs.newLine();
    tgs.append("...");
    tgs.newLine();

  }

  private static final class PROPS {
    /*package*/ static final SProperty apiVersion$RKxP = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225e00L, 0xcbfdf38c839aa55L, "apiVersion");
    /*package*/ static final SProperty kind$RPVc = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225e00L, 0xcbfdf38c839aa57L, "kind");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink templateMetadata$BXdE = MetaAdapterFactory.getContainmentLink(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225e00L, 0xcbfdf38c8397c0eL, "templateMetadata");
  }
}
