package HelmCharts.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class HelmChartValues_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.valueReferences$kEvN)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode ref) {
        tgs.append(SPropertyOperations.getString(ref, PROPS.key$i79E));
        tgs.append(": ");
        tgs.append(SPropertyOperations.getString(ref, PROPS.value$i7BG));
        tgs.newLine();
      }
    });
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink valueReferences$kEvN = MetaAdapterFactory.getContainmentLink(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd7637c9ab225e01L, 0xd4e0ced66b4a2e8L, "valueReferences");
  }

  private static final class PROPS {
    /*package*/ static final SProperty key$i79E = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd4e0ced66b4a2e2L, 0xd4e0ced66b4a2e3L, "key");
    /*package*/ static final SProperty value$i7BG = MetaAdapterFactory.getProperty(0x3b6d7df4fc2241a3L, 0x8f3defa521cb700cL, 0xd4e0ced66b4a2e2L, 0xd4e0ced66b4a2e5L, "value");
  }
}
